### ISSUE TITLE
Docs unreadable on iPad 

### ISSUE THREAD

**Issue by MarkPieszak** [MicrosoftDocs/Docs#37]
iPad air2, it looks like there are some media queries that are causing this?

![image](https://cloud.githubusercontent.com/assets/2574412/20464830/59488952-af1d-11e6-85bb-a4163d391a2e.jpg)

**Comment by PatAltimore** [comment]
Closing issue.

**Comment by MarkPieszak** [comment]
Not a problem! Excellent 👍

**Comment by MarkPieszak** [comment]
Unfortunately still bugged :(
Restarted the iPad air2 etc still comes out the same?

Page link: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection

![image](https://cloud.githubusercontent.com/assets/2574412/20628991/341dc5e2-b2f7-11e6-9f7f-d005f1d1d307.jpg)

**Comment by PatAltimore** [comment]
Thanks @MarkPieszak.  I'll pass this along to the right team.

**Comment by dend** [comment]
We've made template adjustments. This should now be fixed.
