### ISSUE TITLE
add RSS feed to docs.microsoft.com

### ISSUE THREAD

**Issue by thdotnet** [MicrosoftDocs/Docs#51]
Hi,

in order to help keeping the localized version of docs.microsoft, I was wondering if it wouldn`t be a good idea adding a RSS feed. With that, we could track the updates and new articles besides reviewing the initial translation more easily.

Cheers,

**Comment by mairaw** [comment]
Oi @thdotnet! 

RSS feed is one of the top requests on our UserVoice site: https://msdocs.uservoice.com/forums/364242-site-feedback/suggestions/16608964-rss-feed

I suggest you vote up and indicate in the comments how you want to use that feature. We're working on enabling that for our site.

Thanks!

**Comment by dend** [comment]
Hello! The RSS feed is already available - check it out in docs.microsoft.com search results:

![image](https://user-images.githubusercontent.com/1389609/37641835-6c0ca36e-2bd8-11e8-9805-3a7c133d5b89.png)

If you need to submit more feedback, please use https://aka.ms/sitefeedback.
