### ISSUE TITLE
Docs Website repo?

### ISSUE THREAD

**Issue by natelaff** [MicrosoftDocs/Docs#53]
Is one of these repos the actual docs website that shows how you're building these navigation lists and loading the markdown files? Cause I'll tell ya... the docs website is a beautiful site and would love to see how that's done :)

**Comment by mairaw** [comment]
Thank you for your feedback. but unfortunately, the publishing system is not open source. At least, not for now.  

You can vote up on this User Voice issue that requests that: https://msdocs.uservoice.com/forums/364242-site-feedback/suggestions/13760592-make-the-system-open-source

Now, if you're looking for a documentation generator tool, you can see https://dotnet.github.io/docfx/. It's one of the many tools involved in the docs publishing pipeline.

**Comment by evil-shrike** [comment]
@mairaw it's a pity that hte engine isn't open, what about TypeScript doc generation - is a toolschain that is used for generating markdown (I guess) from *.ts available somewhere?

**Comment by mairaw** [comment]
I don't know @evil-shrike. @dend @EisenbergEffect can you guys help?

**Comment by EisenbergEffect** [comment]
One of the tricks with docs.microsoft.com is that the tech behind it can't really be distilled into a single asp.net site, for example. There are many, many components, some of which are tied to very Microsoftie things. One example is the integration of the localization pipeline. We have on our roadmap a number of items to "reshape" the architecture. I'm hopeful that that paves a way to open up more and more parts of the platform in the future.

**Comment by evil-shrike** [comment]
@EisenbergEffect yeah, thanks for info, I understand that it's kinda a pipeline, but my question was about generating docs for TypeScript API, do you have any info on that?

**Comment by EisenbergEffect** [comment]
@evil-shrike For TypeScript, I highly recommend that you take a look at [TypeDoc](http://typedoc.org/). I believe that TS pipeline is built on top of that. I've also used that to help generate the [Aurelia](http://aurelia.io/docs/api) API documentation. The Aurelia site and all documentation is generated, using a custom CLI that takes Markdown and d.ts files as input and produces the site you see there. I hope to open source that eventually, but it needs some work first. The main idea is that TypeDoc can either product HTML for you, or it can give you a JSON object graph representing your API. That's what I use. I then just use a templating engine to iterate the API model and generate the UI I want. (I do a bit of pre-processing on the model before I generate the views as well.)

**Comment by dend** [comment]
@evil-shrike like @EisenbergEffect mentioned, we are using TypeDoc behind the scenes to get raw JSON, that is later piped through [type2docfx](https://github.com/docascode/type2docfx) to get the YAML that can be published through [DocFX](http://dotnet.github.io/docfx/).

Caveat here is that outside the DocFX toolchain, we are not officially supporting any extensions mentioned here, so they can break at any point - while we will properly integrate the changes to docs.microsoft.com, we cannot extend that guarantee to sites outside our system.

**Comment by dend** [comment]
Closing this issue. See relevant link: https://github.com/MicrosoftDocs/feedback/issues/195
