### ISSUE TITLE
VS Docker Support and .dcproj documentation?

### ISSUE THREAD

**Issue by matjazmav** [MicrosoftDocs/Docs#55]
When I try to run app from VS 2017 via Docker, VS try to open web app with IE ([image](http://prntscr.com/gqvp1r)). But I don't have IE enabled. I want to use Edge or Chrome, but don't know how to set this. I was searching for documentation but found nothing useful.

**Comment by mairaw** [comment]
We're working on updates for the docs. /cc @JRAlexander 

@spboyer can you help with this question?

**Comment by mairaw** [comment]
Just one question: when you'll start your debugging, do you see Docker as your choice? Or are you seeing IE as the selected option?

![image](https://user-images.githubusercontent.com/12971179/30985164-563c0ac8-a444-11e7-9eb2-9e0ea4c7dba1.png)

**Comment by spboyer** [comment]
Click the drop down icon next to "Start" project button and choose your web browser

![image](https://user-images.githubusercontent.com/7681382/30985221-acd53e72-a45d-11e7-8f63-1cb59655496b.png)

**Comment by matjazmav** [comment]
@mairaw @spboyer  Yes, I see Docker next to play button. I have docker-compose project selected as start up project.

**Comment by spboyer** [comment]
See the image that I posted here, this is how you select the browser to be launched when the application is launched.

**Comment by matjazmav** [comment]
@spboyer Well in my case I can't select browser. 
![image](https://user-images.githubusercontent.com/9011654/30985624-1f7116da-a491-11e7-85a4-1099282b42fc.png)

**Comment by spboyer** [comment]
Select your web project as the start up project.

**Comment by matjazmav** [comment]
But then Docker wont be used.

**Comment by spboyer** [comment]
No Docker is still a startup option. You should have Docker, IIS Express, <AppName> which is Kestrel **if this a .NET Core App** - in the list.

**Comment by matjazmav** [comment]
I'll try to explain again.
I have created empty .NET Core Web API project with enabled Docker support. Then I select docker-compose project as StartUp Project and click on Run button (Docker). When application starts VS open popup window like this: 
![image](https://user-images.githubusercontent.com/9011654/30986206-eb9b2e66-a492-11e7-9aae-6c9cf00c9d9c.png)

I know I can run web app with IIS or Kestrel, but in this case I want to use Docker.

**Comment by matjazmav** [comment]
Maybe is some setting in `docker-compose.dcproj` file but I couldn't found any documentation about it:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" Sdk="Microsoft.Docker.Sdk">
  <PropertyGroup Label="Globals">
    <ProjectVersion>2.0</ProjectVersion>
    <DockerTargetOS>Linux</DockerTargetOS>
    <ProjectGuid>9fcf6649-118c-4a29-b225-d0ce92302a3f</ProjectGuid>
    <DockerLaunchBrowser>True</DockerLaunchBrowser>
    <DockerServiceUrl>http://localhost:{ServicePort}/api/values</DockerServiceUrl>
    <DockerServiceName>rundocker</DockerServiceName>
  </PropertyGroup>
  <ItemGroup>
    <None Include="docker-compose.ci.build.yml" />
    <None Include="docker-compose.override.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </None>
    <None Include="docker-compose.yml" />
  </ItemGroup>
</Project>
```

**Comment by spboyer** [comment]
Totally understand what you are trying to accomplish.
What you need to do in order to get the Browser option is to set the web project as your startup project. Make the selection as noted in this image.

![image](https://user-images.githubusercontent.com/7681382/30986781-969d6954-a462-11e7-9151-77a67d19c8cd.png)

Then **re-select** the Docker project as your startup project and you should be good to go.

**Comment by matjazmav** [comment]
I have Microsoft Edge already selected, Internet Explorer is not even on list, because I have turned it off in Windows Features. I have tried switching to Google Chrome but same happens.

**Comment by spboyer** [comment]
ok. This is not a Docker (.dcproj) issue. It appears as if there is Visual Studio bump here.  What version are you running?

**Comment by matjazmav** [comment]
15.3.5 Community. Just updated from 15.3.4 hoping to solve this issue.

**Comment by spboyer** [comment]
ok, me too. I just ran through the scenario with no issues. The only thing I "don't" have is the IE disabled in Windows.

**Comment by spboyer** [comment]
Post the scenario here: https://developercommunity.visualstudio.com/spaces/8/index.html with a link to this issue.

**Comment by matjazmav** [comment]
Link to report [here](https://developercommunity.visualstudio.com/content/problem/121827/run-with-docker-select-web-browsers.html). And thanks for help @mairaw and @spboyer  :)

**Comment by spboyer** [comment]
cc:/ @SteveLasker - not sure if this is a tooling issue, VS, etc.

**Comment by SteveLasker** [comment]
It is a tooling issue. VS Container Tools uses the hosts default browser.

**Comment by arroyc** [comment]
@matjazmav  ... current workaround is (assuming you are using windows 10) .. go to default app settings in start menu and change your default web browser to whatever you like.  Looks like there is an issue/dependency with IE, so disabling IE is causing this issue. We are working on it. @spboyer  @SteveLasker  fyi ...

**Comment by JRAlexander** [comment]
Assuming we can close this.

**Comment by dend** [comment]
Closing this given that it's product feedback and has been called out by @arroyc.
