### ISSUE TITLE
Encoding is causing issues when saved/printed to pdf

### ISSUE THREAD

**Issue by inhifistereo** [MicrosoftDocs/Docs#56]
On lines 34-48, there are X's and checkmarks used to denote availability of services in Azure AD DS: https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory-domain-services/active-directory-ds-comparison.md. On the public Docs site there is the option to Download the info to PDF (https://docs.microsoft.com/pdfstore/en-us/Azure.azure-documents/live/active-directory-domain-services.pdf). It would appear there is an issue with the encoding as the X's and checkmarks are coming out as boxes instead.

**Comment by mairaw** [comment]
Thanks for your feedback @inhifistereo. I have filed an internal bug to investigate this issue (#1128819).

/cc @mahesh-unnikrishnan

**Comment by mairaw** [comment]
The engineering team said they couldn't repro the issue and when I went to check again, the issue appeared to be fixed. Can you confirm @inhifistereo? Thanks!

**Comment by inhifistereo** [comment]
Fixed. Thanks.
