### ISSUE TITLE
Error in EnvDTE.ToolBoxItems.Add code sample, no way to edit

### ISSUE THREAD

**Issue by jnm2** [MicrosoftDocs/Docs#57]
In the second code sample under https://docs.microsoft.com/en-us/dotnet/api/envdte.toolboxitems.add#Examples, it has `"C:\Libraries\ADotNetControl.dll("` where I believe it's supposed to just be `"C:\Libraries\ADotNetControl.dll"`.

Why can't I submit a PR for this?

**Comment by dend** [comment]
Closing in favor of https://github.com/MicrosoftDocs/feedback/issues/246

Please make sure to address any additional feedback to https://aka.ms/sitefeedback
