### ISSUE TITLE
Where are my comments?

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/Docs#59]
I just got an email alert from livefyre.com but I don't see the comments on the page:

![image](https://user-images.githubusercontent.com/14079228/34213704-fc98b636-e56d-11e7-9cf0-10eb063bfc49.png)

---

Do you see these comments on this page [Working with multiple environments in ASP.NET Core | Microsoft Docs ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?hubRefSrc=email&utm_source=lfemail&utm_medium=email)?

---

This is not the first time I've seen this either.

**Comment by mairaw** [comment]
Your comment is on a side note, so you have to click on the bubble to see it:
![image](https://user-images.githubusercontent.com/12971179/34222291-f1f67e0a-e56f-11e7-9101-8b94e56c5334.png)

**Comment by spottedmahn** [comment]
ah, forgot about those!  thanks!

**Comment by mairaw** [comment]
No worries!
