### ISSUE TITLE
Sidenote Scrolling Issue

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/Docs#60]
When I open [this sidenote](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?hubRefSrc=email&utm_source=lfemail&utm_medium=email&tabs=aspnetcore2x#create-the-iis-website), it scrolls down to the bottom of the section, why?  I lose my context.

![image](https://user-images.githubusercontent.com/14079228/34254798-c9525706-e61b-11e7-868a-6ce0abe81595.png)

Upon clicking, it displays this:

![image](https://user-images.githubusercontent.com/14079228/34254834-eff13198-e61b-11e7-840f-f3f335469a2a.png)

**Comment by mairaw** [comment]
I'm not reproing this behavior @spottedmahn. What browser are you using?

**Comment by spottedmahn** [comment]
![image](https://user-images.githubusercontent.com/14079228/34271066-b97f0508-e658-11e7-9e20-418cfe8119c9.png)

**Comment by spottedmahn** [comment]
Just tried Edge and it works nicely 😄 

![image](https://user-images.githubusercontent.com/14079228/34271124-eed7e06c-e658-11e7-858b-fb7b2ab2f752.png)

**Comment by spottedmahn** [comment]
I'm guessing with this announcement, [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs), this issue is no longer applicable.
