### ISSUE TITLE
Easy Anchor Links

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/Docs#61]
I love anchor links, they make it so much easier to share specific info on a page.  The issue I have is that it is tedious to currently create them.  I have to inspect the element, get the `id`, update the url with `#[id]`.

Can you please add an 'easy button' for this?

Example [anchor link](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?hubRefSrc=email&utm_source=lfemail&utm_medium=email&tabs=aspnetcore2x#create-the-iis-website).

---

Example of an [easy button](https://github.com/spottedmahn/Experiments/blob/master/Can%20I%20Start%20IIS%20Express/Can%20I%20Start%20IIS%20Express/Startup.cs#L21):

![image](https://user-images.githubusercontent.com/14079228/34254983-87dfbb0a-e61c-11e7-9b6b-eb5b040743bc.png)

**Comment by mairaw** [comment]
Just so I understand your request @spottedmahn, are you saying that you'd like an easy way to copy the anchor link?

Similar to the little anchors we had when you'd hover over headings on MSDN?
https://msdn.microsoft.com/en-us/library/1s46s4ew(v=vs.90).aspx

![image](https://user-images.githubusercontent.com/12971179/34269942-39e77a0e-e63b-11e7-8767-cb8d01111a73.png)

**Comment by spottedmahn** [comment]
Exactly!

**Comment by mairaw** [comment]
Cool. I'll a file an internal feature request for that.

BTW, we do have a UserVoice site for docs.microsoft.com suggestions:
https://aka.ms/sitefeedback

**Comment by spottedmahn** [comment]
Cool!

I know, it's just so limiting.  GitHub issues offer so much more when it comes to explaining the idea.

Perhaps I'll create a UserVoice item an link it to a GitHub issue.

**Comment by mairaw** [comment]
I've created the internal feature request.

@dend do you think he needs to also file a UserVoice item?

**Comment by dend** [comment]
@mairaw one of the PMs on @EisenbergEffect's team is already looking into this - make sure you include him on the request.

**Comment by EisenbergEffect** [comment]
We have the spec and design complete. It's been reviewed with engineering as well. So, it's just waiting to be scheduled in a sprint.

**Comment by spottedmahn** [comment]
Sweet!

![image](https://user-images.githubusercontent.com/14079228/35580376-d75ed72e-05b6-11e8-924e-9496a72f9861.png)

Yep, I see it!

**Comment by EisenbergEffect** [comment]
Glad you like it! We'll keep trying to make additional site experience improvements like this incrementally. I've got a bunch more in the backlog :)
