### ISSUE TITLE
Broken link on homepage

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/Docs#64]
As of 5:52 PM EST on 2018-02-03, the "Microsoft 365 Business" link on the docs.microsoft.com homepage is broken; clicking it gives a 404. The 404 page contains five "related items," the first of which is the correct link the Microsoft 365 Business docs.

* Broken link: <https://docs.microsoft.com/en-us/microsoft-365-business/>
* Correct link: <https://docs.microsoft.com/en-us/microsoft-365/business/>

Thanks for taking care of this!

**Comment by mairaw** [comment]
Thanks for the feedback. They've fixed the redirection since then. 

@dend can you close this?

**Comment by dend** [comment]
Closing.
