### ISSUE TITLE
Prevent Loss of Data on GitHub Issues Feedback System

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/Docs#65]
If I start a GitHub issue using the [new feedback system](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs) and I navigate away or refresh, my post is lost.

Can you this be improved?

- Warn the user
- Preserve the data.  If I refresh the page on an unsubmitted GitHub issue on GitHub.com, nothing is lost.  That is very nice.

**Comment by dend** [comment]
Closing in favor of https://github.com/MicrosoftDocs/feedback/issues/247

Please make sure to open additional feedback in https://aka.ms/feedback
