### ISSUE TITLE
Disable Give documentation feeback when Error loading feedback

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/Docs#66]
I tried providing documentation feedback but when I submitted it, it failed.

![image](https://user-images.githubusercontent.com/14079228/36795066-058b0b16-1c70-11e8-92cc-e14ddba70101.png)

![image](https://user-images.githubusercontent.com/14079228/36795117-28699198-1c70-11e8-8d53-421ae424695a.png)

---

I'm guessing I shouldn't have been able to provide feedback in this state:

![image](https://user-images.githubusercontent.com/14079228/36794850-7de2c64a-1c6f-11e8-8959-d0aaba18c543.png)

[Twitter reference](https://twitter.com/spottedmahn/status/968863202837745664)

**Comment by mairaw** [comment]
Can we close this @spottedmahn? It seems that the issue was fixed already according to your tweet and the new issues I see logged.

**Comment by spottedmahn** [comment]
Yes, thanks!
