### ISSUE TITLE
Dotnet new: documentation on template parameter defaults

### ISSUE THREAD

**Issue by seancpeters** [MicrosoftDocs/Docs#67]
When a parameter does not specify a default value, what occurs is not intuitive ot authors or users. When this is the case, the "replaces" value is used as the default unless the parameter is marked as required. In most cases during template invocation, this will quietly do what would be expected, but not always. For example, for choice parameters when the default value (explicitly defined or from the "replaces" value) is not a valid choice, an "invalid parameter" error is reported both when attempting to invoke the template and when displaying help for the template.

I would be happy to work with the doc authors on fleshing out the details of this documentation (I'm a dev on dotnet new)

**Comment by mairaw** [comment]
Hi @seancpeters! I’m the writer for dotnet new. We should move this discussion to the dotnet/docs repo.

**Comment by mairaw** [comment]
Move to https://github.com/dotnet/docs/issues/4626. I don't have permission to close this @dend. Can you see if you can?

Perhaps we should close the issues here so people use the new repo for feedback? Is this repo being used for anything at the moment? It seems it contains an old version of the contributor guide.

**Comment by dend** [comment]
@mairaw I can close this. Yes, users should always use documentation repos for doc-specific feedback, and https://github.com/MicrosoftDocs/feedback for site feedback.
