### ISSUE TITLE
Consider Providing Ability to Reference Specific Paragraph of Issue

### ISSUE THREAD

**Issue by Mike-EEE** [MicrosoftDocs/Docs#68]
First off, amazing -- and clever, really -- work with integrating the documents system with GitHub.  Although I was a fan of using Disqus over LiveFyre when the that decision was made, using GitHub is better than both of them all around.

This request is to ask for the ability to comment/reference a particular paragraph within the document to provide better context between user and authors.  Please see this issue for context of some context: 😆 
https://github.com/MicrosoftDocs/azure-docs/issues/5955#issuecomment-374447456

Additionally, consider somehow making this the Title of the submitted issue (or part of the title at least), so that the user does not have to type in the title for the issue.  In thinking of a commenting system, titles are not used and seem passé in the way of outlook/email, etc.  GitHub is a little more formal than a social media commenting system, but we were all trained as such with the old way of doing things. 😄   In any case, providing the actual paragraph somehow as the starter title would address this issue.

Thank you for any consideration!

**Comment by dend** [comment]
Closing in favor of https://github.com/MicrosoftDocs/feedback/issues/248

Please make sure to open any additional feedback on https://aka.ms/sitefeedback
