### ISSUE TITLE
Consider Item-level "View on GitHub"

### ISSUE THREAD

**Issue by Mike-EEE** [MicrosoftDocs/Docs#70]
There is a "View on GitHub" link for the entire list of issues.  It would be valuable/useful to have this same functionality for each individual item as well.  Thank you for any consideration in having this developed.

**Comment by dend** [comment]
Closing in favor of https://github.com/MicrosoftDocs/feedback/issues/249

Please make sure to open new feedback items in https://aka.ms/sitefeedback
